# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: db_clustering 0.1.17 ruby lib

Gem::Specification.new do |s|
  s.name = "db_clustering"
  s.version = "0.1.17"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Cihat G\u{fc}nd\u{fc}z"]
  s.date = "2015-07-20"
  s.description = "Big-Data clustering algorithms in Ruby (on Rails). Currently only supports DBSCAN algorithm and ActiveRecord database."
  s.email = "CihatGuenduez@posteo.de"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "db_clustering.gemspec",
    "lib/algorithms/density_based/dbscan.rb",
    "lib/datasource_adapters/active_record.rb",
    "lib/datasource_adapters/in_memory.rb",
    "lib/db_clustering.rb",
    "lib/distance_metrics/average_difference.rb",
    "lib/distance_metrics/cosine_similarity.rb",
    "lib/distance_metrics/euclidean_distance.rb",
    "lib/distance_metrics/pearson_correlation.rb",
    "lib/generators/datasource/active_record.rb",
    "lib/models/cluster.rb",
    "lib/models/point.rb",
    "lib/models/vector.rb",
    "spec/algorithms/density_based/dbscan_spec.rb",
    "spec/datasource_adapters/active_record_spec.rb",
    "spec/datasource_adapters/in_memory_spec.rb",
    "spec/distance_metrics/average_difference_spec.rb",
    "spec/distance_metrics/cosine_similarity_spec.rb",
    "spec/distance_metrics/euclidean_distance_spec.rb",
    "spec/distance_metrics/pearson_correlation_spec.rb",
    "spec/generators/datasource/active_record_spec.rb",
    "spec/models/cluster_spec.rb",
    "spec/models/point_spec.rb",
    "spec/models/vector_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/dataset_helper.rb",
    "spec/support/test_model.rb"
  ]
  s.homepage = "http://github.com/Flinesoft/db_clustering"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Big-Data clustering algorithms in Ruby (on Rails)."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 4.2.1", "~> 4.2"])
      s.add_development_dependency(%q<rspec>, [">= 3.2.0", "~> 3.0"])
      s.add_development_dependency(%q<rdoc>, [">= 4.2.0", "~> 4.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.10.2", "~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 4.5.1", "~> 4.0"])
      s.add_development_dependency(%q<byebug>, ["~> 5.0"])
      s.add_development_dependency(%q<awesome_print>, [">= 1.6.1", "~> 1.6"])
      s.add_development_dependency(%q<fuubar>, [">= 2.0.0.rc1", "~> 2.0"])
      s.add_development_dependency(%q<simple-random>, [">= 1.0.0", "~> 1.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 4.2.1", "~> 4.2"])
      s.add_dependency(%q<rspec>, [">= 3.2.0", "~> 3.0"])
      s.add_dependency(%q<rdoc>, [">= 4.2.0", "~> 4.0"])
      s.add_dependency(%q<bundler>, [">= 1.10.2", "~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 4.5.1", "~> 4.0"])
      s.add_dependency(%q<byebug>, ["~> 5.0"])
      s.add_dependency(%q<awesome_print>, [">= 1.6.1", "~> 1.6"])
      s.add_dependency(%q<fuubar>, [">= 2.0.0.rc1", "~> 2.0"])
      s.add_dependency(%q<simple-random>, [">= 1.0.0", "~> 1.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 4.2.1", "~> 4.2"])
    s.add_dependency(%q<rspec>, [">= 3.2.0", "~> 3.0"])
    s.add_dependency(%q<rdoc>, [">= 4.2.0", "~> 4.0"])
    s.add_dependency(%q<bundler>, [">= 1.10.2", "~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 4.5.1", "~> 4.0"])
    s.add_dependency(%q<byebug>, ["~> 5.0"])
    s.add_dependency(%q<awesome_print>, [">= 1.6.1", "~> 1.6"])
    s.add_dependency(%q<fuubar>, [">= 2.0.0.rc1", "~> 2.0"])
    s.add_dependency(%q<simple-random>, [">= 1.0.0", "~> 1.0"])
  end
end

